### ISSUE TITLE
Error with grunt server

### ISSUE THREAD

**Issue by ghost** [myflowpl/generator-angular-flow#1]
Hi! 
I can run yo angular-flow without errors. When I try to run the application with "grunt server" I get following error message:

grunt server
Running "compass:dev" (compass) task
directory public/css
    error public/styles/main.scss (Line 19: File to import not found or unreadable: float-label.
Load paths:
  E:/playground/s20/public/bower_components
  Compass::SpriteImporter
  E:/playground/s20/public/styles
  C:/Ruby22/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/stylesheets)

What could be the problem?

**Comment by myflowpl** [comment]
it looks like _ float-label.scss is missing
try to comment out inmort statment inside styles/main.scss
i'll commit the file soon

**Comment by ghost** [comment]
yep, that solved it
