### ISSUE TITLE
add library npm

### ISSUE THREAD

**Issue by FlorianBurgevin** [myflowpl/generator-angular-flow#8]
Hello,

How can I add an npm library and use it all over my project?

I did: npm install -g moment --save-dev

and then add in common.js
require('moment');

But I can use it on my code.

**Comment by leonanluppi** [comment]
Hey,

You need add on your file which you will use module.

Ex:

my-module.js

```
var moment = require('moment');

console.log(moment);
```

**Comment by FlorianBurgevin** [comment]
Thank you for the answer !

I solved the problem few days ago.

I can add globally moment with just add in common.js :

moment = require('moment');
